/* Oficina Editorial: dashboard assimétrico, carvão/papel mineral/óxido; métricas sempre conduzem a decisões e a IA permanece sob autoria humana. */
import { useMemo, useState } from "react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Activity, ArrowUpRight, Bot, CalendarDays, Check, ChevronRight, CircleHelp, FlaskConical, Gauge, GitBranch, Layers3, Menu, Play, ShieldCheck, Sparkles, Target, Users, X } from "lucide-react";
import { toast } from "sonner";

const asset = (name: string) => `/manus-storage/${name}`;
const audience = [{ month: "Ago", followers: 71, streams: 340 }, { month: "Set", followers: 145, streams: 820 }, { month: "Out", followers: 310, streams: 1840 }, { month: "Nov", followers: 520, streams: 3100 }];
const contentMix = [{ name: "Vídeo curto", value: 42, color: "#C84732" }, { name: "Arte + legenda", value: 28, color: "#d7d2c9" }, { name: "Bastidores", value: 18, color: "#827a70" }, { name: "Manifesto", value: 12, color: "#f0c65a" }];
const experiments = [
  { id: "EXP-07", title: "Teaser com assinatura vocal", audience: "Fã de metal extremo", window: "24 out — 06 nov", status: "Em preparação", hypothesis: "A voz humana como âncora aumenta salvamentos em 20%.", color: "oxide" },
  { id: "EXP-06", title: "Carrossel hebraico + tradução", audience: "Diáspora / hebraico", window: "10 — 23 out", status: "Aprendizado registrado", hypothesis: "A camada linguística cria comentários mais qualificados.", color: "yellow" },
  { id: "EXP-05", title: "Lobo de ferro em movimento", audience: "Darkwave / cyberpunk", window: "26 set — 09 out", status: "Concluído", hypothesis: "A estética compartilhável abre entrada fora do metal.", color: "stone" },
];

function Metric({ label, value, delta, note, accent = "oxide" }: { label: string; value: string; delta: string; note: string; accent?: string }) {
  return <div className={`metric-card ${accent}`}><div className="metric-label">{label}<span className="metric-delta">{delta}</span></div><div className="metric-value">{value}</div><div className="metric-note">{note}</div></div>;
}

export default function Home() {
  const [active, setActive] = useState("Visão geral");
  const [sidebar, setSidebar] = useState(false);
  const [simulated, setSimulated] = useState(false);
  const [selectedExperiment, setSelectedExperiment] = useState(experiments[0]);
  const chartData = useMemo(() => simulated ? audience.map((item, index) => ({ ...item, followers: Math.round(item.followers * (1 + index * .15)), streams: Math.round(item.streams * (1 + index * .2)) })) : audience, [simulated]);
  const nav = [{ label: "Visão geral", icon: Gauge }, { label: "Experimentos", icon: FlaskConical }, { label: "Público", icon: Users }, { label: "Governança", icon: ShieldCheck }, { label: "Plano até 07 nov", icon: CalendarDays }];
  const runSimulation = () => { setSimulated(true); toast.success("Ciclo simulado executado", { description: "O cenário de 14 dias foi recalculado com base na hipótese EXP-07." }); };

  return <div className="app-shell">
    <aside className={`sidebar ${sidebar ? "open" : ""}`}>
      <div className="brand"><img src={asset("dvorah-forge-mark_67cd37a0.png")} /><div><span className="eyebrow">LAB / 01</span><strong>DVORAH</strong><small>motor de divulgação IA</small></div><button className="close-mobile" onClick={() => setSidebar(false)}><X size={18} /></button></div>
      <div className="side-rule" />
      <div className="side-caption">Mapa de trabalho</div>
      <nav>{nav.map(({ label, icon: Icon }) => <button key={label} className={active === label ? "active" : ""} onClick={() => { setActive(label); setSidebar(false); }}><Icon size={17} /><span>{label}</span>{active === label && <ChevronRight size={14} />}</button>)}</nav>
      <div className="sidebar-bottom"><div className="status-dot" /><div><b>Simulação ativa</b><span>Dados não operacionais</span></div><CircleHelp size={16} /></div>
    </aside>
    {sidebar && <div className="mobile-scrim" onClick={() => setSidebar(false)} />}
    <main className="main-content">
      <header className="topbar"><button className="mobile-menu" onClick={() => setSidebar(true)}><Menu size={21} /></button><div><span className="breadcrumb">PROJETO / DVORAH / {active.toUpperCase()}</span><h1>{active === "Visão geral" ? "O estado da descoberta" : active}</h1></div><div className="top-actions"><span className="date-pill"><span className="live-dot" /> 14 AGO — 07 NOV 2026</span><button className="icon-btn" onClick={() => toast("Todas as métricas estão marcadas como simuladas.")}><CircleHelp size={18} /></button></div></header>

      {active === "Visão geral" && <>
        <section className="hero-band"><div className="hero-copy"><div className="stamp"><span /> DIAGNÓSTICO 01 / 04</div><h2>A infraestrutura já existe.<br /><em>Agora prove o que move a descoberta.</em></h2><p>Um laboratório para testar formatos, públicos e cadências de divulgação sem terceirizar a assinatura artística do Dvorah.</p><div className="hero-actions"><button className="primary-btn" onClick={runSimulation}><Play size={15} fill="currentColor" /> Rodar experimento de 14 dias</button><button className="text-btn" onClick={() => setActive("Governança")}>Ver anel autoral <ArrowUpRight size={15} /></button></div></div><div className="hero-art"><div className="art-register">EVIDÊNCIA 04 <span /> ARQUIVO DE CAMPANHA</div><img src={asset("dvorah-campaign-iron-wolf_83aef3c3.jpg")} onError={(event) => { event.currentTarget.style.display = "none"; }} /><div className="art-sigil">03<br /><small>blades / loop / human</small></div><div className="art-caption">ARTE DE CAMPANHA / EXP-07<br /><b>conteúdo humano-ampliado</b></div></div></section>
        <div className="simulation-banner"><Sparkles size={16} /><span><b>Modo simulado.</b> Os números abaixo são hipóteses de trabalho para a entrega até 07 de novembro.</span>{simulated ? <span className="sim-done"><Check size={14} /> EXP-07 recalculado</span> : <span className="sim-tag">BASELINE / AGO 2026</span>}</div>
        <div className="material-strip"><span className="stamp-label">FATO</span><span>8 plataformas ativas · catálogo distribuído · audiência ainda em construção</span><span className="line-mark" /></div><section className="metrics-grid"><Metric label="Seguidores somados" value={simulated ? "84" : "71"} delta="+18% alvo" note="Meta de ciclo: 85" /><Metric label="Streams / mês" value={simulated ? "410" : "340"} delta="+20% alvo" note="Base pública estimada" accent="stone" /><Metric label="Constância editorial" value="1 / sem" delta="N2 em curso" note="Meta: 3 posts / sem" accent="yellow" /><Metric label="Custo do motor" value="R$ 180" delta="— 40%" note="Cenário central mensal" accent="stone" /></section>
        <section className="dashboard-grid"><div className="panel chart-panel"><div className="evidence-tab">EVIDÊNCIA / 01</div><div className="panel-head"><div><span className="panel-kicker">TRAJETÓRIA / 90 DIAS</span><h3>Tração antes da escala</h3></div><span className="legend"><i className="legend-red" /> seguidores <i className="legend-white" /> streams ÷ 10</span></div><div className="chart-wrap"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chartData}><defs><linearGradient id="redArea" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#C84732" stopOpacity={.35} /><stop offset="100%" stopColor="#C84732" stopOpacity={0} /></linearGradient></defs><CartesianGrid stroke="#35332f" strokeDasharray="2 4" vertical={false} /><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{ fill: "#8b877f", fontSize: 11 }} /><YAxis axisLine={false} tickLine={false} tick={{ fill: "#8b877f", fontSize: 11 }} /><Tooltip contentStyle={{ background: "#201f1d", border: "1px solid #4d4840", borderRadius: 4, color: "#efe9df" }} /><Area type="monotone" dataKey="followers" stroke="#C84732" fill="url(#redArea)" strokeWidth={2} /><Area type="monotone" dataKey={(d) => d.streams / 10} stroke="#d7d2c9" fill="none" strokeWidth={1.5} strokeDasharray="5 4" /></AreaChart></ResponsiveContainer></div><div className="chart-foot"><span><b>N1</b> Presença consolidada</span><span><b>N2</b> Constância em validação</span><span><b>N3</b> Próximo limiar: 1.000</span></div></div>
          <div className="panel next-panel"><div className="evidence-tab oxide-tab">RECOMENDAÇÃO / 01</div><div className="panel-kicker">DECISÃO RECOMENDADA</div><div className="decision-mark">07</div><h3>Voz antes do algoritmo</h3><p>Priorizar um teaser de 20 segundos com a assinatura vocal natural da intérprete e CTA para salvar a faixa.</p><div className="decision-meta"><span>Hipótese</span><b>+20% em salvamentos</b></div><button className="outline-btn" onClick={runSimulation}>Executar hipótese <ArrowUpRight size={15} /></button></div></section>
        <section className="lower-grid"><div className="panel experiments-panel"><div className="panel-head"><div><span className="panel-kicker">CICLO BUILD — MEASURE — LEARN</span><h3>Experimentos recentes</h3></div><button className="small-link" onClick={() => setActive("Experimentos")}>Ver todos <ArrowUpRight size={14} /></button></div>{experiments.map((exp) => <button className="experiment-row" key={exp.id} onClick={() => { setSelectedExperiment(exp); setActive("Experimentos"); }}><span className={`experiment-id ${exp.color}`}>{exp.id}</span><span className="experiment-main"><b>{exp.title}</b><small>{exp.audience} · {exp.window}</small></span><span className="experiment-status">{exp.status}</span><ChevronRight size={15} /></button>)}</div><div className="panel mix-panel"><div className="panel-kicker">FÁBRICA DE CONTEÚDO</div><h3>Mix de formatos</h3><div className="mix-content"><ResponsiveContainer width={130} height={130}><PieChart><Pie data={contentMix} dataKey="value" innerRadius={42} outerRadius={60} paddingAngle={3}>{contentMix.map((item) => <Cell key={item.name} fill={item.color} />)}</Pie></PieChart></ResponsiveContainer><div className="mix-legend">{contentMix.map((item) => <div key={item.name}><i style={{ background: item.color }} /> <span>{item.name}</span><b>{item.value}%</b></div>)}</div></div></div></section>
      </>}

      {active === "Experimentos" && <section className="detail-page"><div className="page-intro"><span className="panel-kicker">MÓDULO M5 / ANÁLISE E ITERAÇÃO</span><h2>O laboratório de hipóteses</h2><p>Todo conteúdo começa como hipótese, passa por um ciclo curto e termina em uma decisão documentada. Nada é escalado sem evidência.</p></div><div className="experiment-layout"><div className="experiment-list">{experiments.map(exp => <button key={exp.id} className={`exp-card ${selectedExperiment.id === exp.id ? "selected" : ""}`} onClick={() => setSelectedExperiment(exp)}><span className={`experiment-id ${exp.color}`}>{exp.id}</span><b>{exp.title}</b><small>{exp.audience}</small><span className="status-line"><i /> {exp.status}</span></button>)}</div><div className="panel experiment-detail"><div className="detail-top"><span className={`experiment-id ${selectedExperiment.color}`}>{selectedExperiment.id}</span><span className="sim-tag">HIPÓTESE</span></div><h3>{selectedExperiment.title}</h3><p className="hypothesis">“{selectedExperiment.hypothesis}”</p><div className="detail-table"><div><span>Janela de teste</span><b>{selectedExperiment.window}</b></div><div><span>Persona primária</span><b>{selectedExperiment.audience}</b></div><div><span>Decisão atual</span><b>Executar em pequena escala</b></div></div><div className="what-changes"><Sparkles size={17} /><div><b>O que isso muda</b><p>Se a hipótese for confirmada, o formato entra no calendário semanal e recebe uma variação bilíngue.</p></div></div><button className="primary-btn" onClick={runSimulation}><Play size={15} fill="currentColor" /> Rodar simulação</button></div></div></section>}
      {active === "Público" && <section className="detail-page"><div className="page-intro"><span className="panel-kicker">MÓDULO M1 / INTELIGÊNCIA DE PÚBLICO</span><h2>Audiência precisa, não massiva</h2><p>Quatro portas de entrada para o mesmo universo: peso, estética, idioma e curiosidade tecnológica.</p></div><div className="persona-grid">{[{n:"01", title:"Fã de metal extremo", text:"25–45 anos · doom / sludge · busca peso atmosférico", channel:"Instagram / Spotify"},{n:"02", title:"Ouvinte darkwave", text:"20–35 anos · cultura visual · compartilha estética", channel:"Reels / TikTok"},{n:"03", title:"Diáspora hebraica", text:"20–50 anos · conexão linguística e cultural", channel:"YouTube / comunidades"},{n:"04", title:"Curioso de IA", text:"18–40 anos · quer ver o processo por trás", channel:"X / Reddit / YouTube"}].map(p => <div className="persona-card" key={p.n}><span>{p.n}</span><h3>{p.title}</h3><p>{p.text}</p><div><Target size={14} /> {p.channel}</div></div>)}</div><div className="panel insight-panel"><GitBranch size={20} /><div><span className="panel-kicker">LEITURA DO MOTOR</span><h3>Núcleo + estética são o primeiro quadrante.</h3><p>O próximo experimento combina a maior afinidade musical com a maior predisposição para compartilhar imagem.</p></div></div></section>}
      {active === "Governança" && <section className="detail-page"><div className="page-intro"><span className="panel-kicker">ANEL AUTORAL / CONTROLE HUMANO</span><h2>A IA apoia. O produtor decide.</h2><p>Uma política simples para impedir que velocidade operacional seja confundida com autoria.</p></div><div className="governance-layout"><div className="governance-ring"><div className="ring-center"><img src={asset("dvorah-forge-mark_67cd37a0.png")} /><b>100%</b><span>decisão humana</span></div><div className="ring-label r1">Composição<br /><small>humana</small></div><div className="ring-label r2">Curadoria<br /><small>visual</small></div><div className="ring-label r3">Aval do<br /><small>lançamento</small></div></div><div className="panel rules-panel"><div className="panel-kicker">CONTRATO INTERNO / 05 REGRAS</div>{["A obra musical tem autor humano identificado.","A voz natural da intérprete não é gerada nem substituída.","Toda arte sintética passa por aprovação manual.","Conteúdo sintético ou ampliado é rotulado.","Letras, prompts e artes finais são arquivados."].map((rule, i) => <div className="rule" key={rule}><span>0{i+1}</span><p>{rule}</p><Check size={16} /></div>)}</div></div></section>}
      {active === "Plano até 07 nov" && <section className="detail-page"><div className="page-intro"><span className="panel-kicker">CRONOGRAMA DE EXECUÇÃO / 12 SEMANAS</span><h2>Da constância à primeira tração</h2><p>Horizonte simulado encerrado na primeira semana de novembro, com entregas que deixam um playbook replicável.</p></div><div className="timeline">{[{q:"01", date:"19 ago — 15 set", title:"Constância", text:"Ativar M1–M4 e publicar três vezes por semana.", tag:"N2"},{q:"02", date:"16 set — 13 out", title:"Tração social", text:"Testar EXP-05 e EXP-06; registrar aprendizado por persona.", tag:"N3"},{q:"03", date:"14 out — 07 nov", title:"Tração de streaming", text:"Executar EXP-07, consolidar métricas e fechar o playbook.", tag:"N4"}].map(item => <div className="timeline-item" key={item.q}><span className="timeline-num">{item.q}</span><div><span className="panel-kicker">{item.date} · {item.tag}</span><h3>{item.title}</h3><p>{item.text}</p></div><ArrowUpRight size={16} /></div>)}</div></section>}
      <footer><span>DVORAH / LAB 01</span><span>Ambiente acadêmico simulado · versão 0.1</span><span>build — measure — learn</span></footer>
    </main>
  </div>;
}
